//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marches_Deconfines
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategorieUtilisateur
    {
        public int CategorieUtilisateurId { get; set; }
        public int utilisateurId { get; set; }
        public int categorieId { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
