//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marches_Deconfines
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarcheD14Entities : DbContext
    {
        public MarcheD14Entities()
            : base("name=MarcheD14Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<Categorie> Categories { get; set; }
        public virtual DbSet<CategorieUtilisateur> CategorieUtilisateurs { get; set; }
        public virtual DbSet<Commande> Commandes { get; set; }
        public virtual DbSet<LieuLivraison> LieuLivraisons { get; set; }
        public virtual DbSet<Panier> Paniers { get; set; }
        public virtual DbSet<Paymment> Paymments { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Sm> Sms { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
    }
}
