//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marches_Deconfines
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paymment
    {
        public int paymmentId { get; set; }
        public Nullable<System.DateTime> datePaymment { get; set; }
        public string numCompte { get; set; }
        public string telACommercant { get; set; }
        public string telUtilisateur { get; set; }
        public Nullable<int> utilisateurId { get; set; }
        public Nullable<int> commandeId { get; set; }
    
        public virtual Commande Commande { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
