//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marches_Deconfines
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilisateur()
        {
            this.Articles = new HashSet<Article>();
            this.CategorieUtilisateurs = new HashSet<CategorieUtilisateur>();
            this.Commandes = new HashSet<Commande>();
            this.Paymments = new HashSet<Paymment>();
        }
    
        public int utilisateurId { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string adresse { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public string loginUser { get; set; }
        public string mdpUser { get; set; }
        public string LoginErrorMessage { get; set; }
        public Nullable<int> userRole { get; set; }
        public Nullable<int> typeprivilege { get; set; }
        public string descriptionUser { get; set; }
        public string siren { get; set; }
        public string ville { get; set; }
        public string arrondissement { get; set; }
        public Nullable<int> smsid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Articles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategorieUtilisateur> CategorieUtilisateurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commande> Commandes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paymment> Paymments { get; set; }
        public virtual Sm Sm { get; set; }
    }
}
